services:
  splunk:
    image: splunk/splunk:9.2.1
    platform: linux/amd64
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=AcmeCorp2024!
    ports:
      - "8000:8000"   # Web UI
      - "8088:8088"   # HTTP Event Collector (ingesta de logs)
    volumes:
      - splunk-data:/opt/splunk/var
    restart: unless-stopped

volumes:
  splunk-data:
